### ISSUE TITLE
is duplication needed?

### ISSUE THREAD

**Issue by kostis-codefresh** [laszlocph/osca#1]
I see

osca.dev/v0.1.0/owner-and-repository

and
osca.dev/v0.0.0/owner
osca.dev/v0.0.0/repository

Maybe keep only the latter two?

Using the first one requires the consumer to do string splitting which I think is not optimal.

**Comment by laszlocph** [comment]
I don't expect every field to be adopted by every tool.
- Some tools use today the format of: `osca.dev/v0.1.0/owner-and-repository`, like Gimlet.
- Some may go for `osca.dev/v0.0.0/owner` + `osca.dev/v0.0.0/repository` format.

This was the idea.

But I understand your concern that a split is a thousand times more difficult than a concat.

Also I see a possible issue down the line with this ambiguity: some tools use the `owner-and-repository` approach and some the other. So you have to special case your OSCA implementation, or ask people to update it for hundreds of repos.

So this decision has consequences down the line and happy to hear your thoughts on this.

**Comment by kostis-codefresh** [comment]
I suggest you only keep 
osca.dev/v0.0.0/owner
osca.dev/v0.0.0/repository

and have Gimlet concat the result for what it needs.

**Comment by laszlocph** [comment]
Removed owner-and-repository in https://github.com/laszlocph/osca/commit/f57055cb2866f3eeb67bf6d213e90eaaf99d7b06
